#!/usr/bin/env node
import { execSync } from "node:child_process";
function tryNpmAudit() {
  try {
    const stdout = execSync("npm audit --json", { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 60_000 });
    const sev = JSON.parse(stdout).metadata?.vulnerabilities ?? {};
    return { high: sev.high ?? 0, critical: sev.critical ?? 0 };
  } catch (err) {
    if (err.stdout) {
      try { const sev = JSON.parse(err.stdout.toString()).metadata?.vulnerabilities ?? {}; return { high: sev.high ?? 0, critical: sev.critical ?? 0 }; } catch { return null; }
    }
    return null;
  }
}
const a = tryNpmAudit();
process.stdout.write(`# Code-quality report

_Auto-generated by \`scripts/quality/generate-report.mjs\` on ${new Date().toISOString()}._

**Plan:** v3.1 — see \`.cursor/skills/code-quality/SKILL.md\`.

## Gated today
- 2. TypeScript (\`astro check\`) ✅
- A1. Wall-time budget wrapper ✅
- 15. Daily code-quality report ✅

${a ? `## npm audit (live)
- High: ${a.high} (target 0) | Critical: ${a.critical} (target 0)
` : ""}

## Compliance gaps
ESLint, husky hooks, fallow, Wallace, alex prose, audit baseline, coverage, theme tokens, contrast, visual regression.
`);
